// <auto-generated />
namespace Dashboard.Infra.Data.Context
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class asd : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(asd));
        
        string IMigrationMetadata.Id
        {
            get { return "202201120047102_asd"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
